import type { Metadata } from 'next';
import { Geist, Geist_Mono, IBM_Plex_Sans_Arabic, Cairo, Baloo_Bhaijaan_2 } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
    variable: '--font-ibm-plex-sans-arabic',
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700'],
});

const cairo = Cairo({
    variable: '--font-cairo',
    subsets: ['latin'],
    weight: ['300', '400', '700', '900'],
});

const baloo = Baloo_Bhaijaan_2({
    variable: '--font-baloo',
    subsets: ['latin'],
    weight: ['400', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='ar' dir='rtl'>
            <body
                className={`${geistSans.variable} overflow-x-hidden ${ibmPlexSansArabic.variable} ${cairo.variable} ${geistMono.variable} font-cairo antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
